/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/app-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Config */
        get: operations["app_config_api_v1_app_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo-results/{event_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Demo Result */
        post: operations["open_demo_result_api_v1_demo_results__event_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elevation-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Elevation Preview */
        post: operations["create_elevation_preview_api_v1_elevation_previews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Resources */
        post: operations["estimate_resources_api_v1_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return readiness information without probing or launching SFINCS.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Event */
        get: operations["rainfall_event_api_v1_rainfall_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/recent-ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Rainfall Ranking
         * @description Return the configured urban-flood rainfall scenarios in rank order.
         */
        get: operations["recent_rainfall_ranking_api_v1_rainfall_recent_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Stations */
        get: operations["rainfall_stations_api_v1_rainfall_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/stations/{station_id}/extremes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Station Extremes */
        get: operations["rainfall_station_extremes_api_v1_rainfall_stations__station_id__extremes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Result */
        post: operations["import_result_api_v1_results_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Result */
        get: operations["export_result_api_v1_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Result */
        get: operations["inspect_result_api_v1_runs__run_id__inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/layers/depth.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Depth Layer */
        get: operations["time_depth_layer_api_v1_runs__run_id__layers_depth_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/layers/elevation.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elevation Layer */
        get: operations["elevation_layer_api_v1_runs__run_id__layers_elevation_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/layers/grid-resolution.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grid Resolution Layer */
        get: operations["grid_resolution_layer_api_v1_runs__run_id__layers_grid_resolution_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/layers/max-depth.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Max Depth Layer */
        get: operations["max_depth_layer_api_v1_runs__run_id__layers_max_depth_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result-energy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Energy Status */
        get: operations["result_energy_status_api_v1_runs__run_id__result_energy_get"];
        put?: never;
        /** Start Result Energy */
        post: operations["start_result_energy_api_v1_runs__run_id__result_energy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result-energy/point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Energy Point */
        get: operations["result_energy_point_api_v1_runs__run_id__result_energy_point_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result-extrema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Extrema */
        get: operations["result_extrema_api_v1_runs__run_id__result_extrema_get"];
        put?: never;
        /** Start Result Extrema */
        post: operations["start_result_extrema_api_v1_runs__run_id__result_extrema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result-extrema/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Extrema Status */
        get: operations["result_extrema_status_api_v1_runs__run_id__result_extrema_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Metadata */
        get: operations["result_metadata_api_v1_runs__run_id__result_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccuracyMode
         * @enum {string}
         */
        AccuracyMode: "full_1m" | "uniform" | "adaptive";
        /** AnalysisArea */
        AnalysisArea: {
            /** Area M2 */
            area_m2: number;
            bounds: components["schemas"]["GeoBounds"];
            center: components["schemas"]["LonLat"];
            /** Height M */
            height_m: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "preset_square" | "rectangle";
            /** Width M */
            width_m: number;
        };
        /** AppConfigResponse */
        AppConfigResponse: {
            /** Allow Result Import */
            allow_result_import: boolean;
            /** Allow Run */
            allow_run: boolean;
            /** Demo Result Event Ids */
            demo_result_event_ids: string[];
            /** Download Url */
            download_url: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "local" | "demo";
        };
        /** CancelRunResponse */
        CancelRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            state: components["schemas"]["RunState"];
        };
        /** ConstantRainfall */
        ConstantRainfall: {
            /**
             * Duration Minutes
             * @default 60
             */
            duration_minutes: number;
            /** Intensity Mm Per H */
            intensity_mm_per_h: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "constant";
        };
        /** ElevationPreviewRequest */
        ElevationPreviewRequest: {
            analysis_area: components["schemas"]["AnalysisArea"];
            /**
             * Grid Cell Size M
             * @default 1
             * @enum {integer}
             */
            grid_cell_size_m: 1 | 2 | 4;
        };
        /** ElevationPreviewResponse */
        ElevationPreviewResponse: {
            bounds: components["schemas"]["GeoBounds"];
            /** Elevation Legend */
            elevation_legend: components["schemas"]["ResultElevationLegendItem"][];
            /**
             * Grid Cell Size M
             * @enum {integer}
             */
            grid_cell_size_m: 1 | 2 | 4;
            /** Height Samples */
            height_samples: number;
            /** Image Url */
            image_url: string;
            /** Nearest Filled Cells */
            nearest_filled_cells: number;
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
            /** Provider Counts */
            provider_counts?: {
                [key: string]: number;
            };
            /** Width Samples */
            width_samples: number;
        };
        /** EngineSummary */
        EngineSummary: {
            /**
             * Required
             * @default SFINCS 2.4.0 Galibier
             * @constant
             */
            required: "SFINCS 2.4.0 Galibier";
        };
        /** GeoBounds */
        GeoBounds: {
            /** East Deg */
            east_deg: number;
            /** North Deg */
            north_deg: number;
            /** South Deg */
            south_deg: number;
            /** West Deg */
            west_deg: number;
        };
        /** GeocodeAttribution */
        GeocodeAttribution: {
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /** GeocodeCandidateResponse */
        GeocodeCandidateResponse: {
            /** Confidence */
            confidence?: number | null;
            /** Converted */
            converted?: string | null;
            /** Lat */
            lat: number;
            /** Level */
            level?: number | null;
            /** Lon */
            lon: number;
            /**
             * Provider
             * @constant
             */
            provider: "csis_simple_geocoding";
            /** Title */
            title: string;
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            attribution: components["schemas"]["GeocodeAttribution"];
            /** Candidates */
            candidates: components["schemas"]["GeocodeCandidateResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Application Version */
            application_version: string;
            engine: components["schemas"]["EngineSummary"];
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** HistoricalObservedProfile */
        HistoricalObservedProfile: {
            /** Available */
            available: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "historical_observed_profile";
            /** Profile Id */
            profile_id?: string | null;
        };
        /** HistoricalUniformRainfall */
        HistoricalUniformRainfall: {
            /** Available */
            available: boolean;
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "historical_uniform";
        };
        /** LonLat */
        LonLat: {
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
        };
        /** PointEnergyResponse */
        PointEnergyResponse: {
            /**
             * Cell Area M2
             * @default 1
             */
            cell_area_m2: number;
            /** Column */
            column: number;
            /** Has Data */
            has_data: boolean;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Rank */
            rank?: number | null;
            /** Row */
            row: number;
            /** Through Time Index */
            through_time_index: number;
            /** Through Time Value */
            through_time_value: string;
            /** Total Energy J */
            total_energy_j?: number | null;
            /** Total Outflow M3 */
            total_outflow_m3?: number | null;
        };
        /** PointInspectionResponse */
        PointInspectionResponse: {
            /** Column */
            column: number;
            /** Depth M */
            depth_m?: number | null;
            /** Grid Resolution M */
            grid_resolution_m?: number | null;
            /** Has Data */
            has_data: boolean;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Max Depth M */
            max_depth_m?: number | null;
            /** Max Time Index */
            max_time_index?: number | null;
            /** Max Time Value */
            max_time_value?: string | null;
            /** Row */
            row: number;
            /** Speed Mps */
            speed_mps?: number | null;
            /** Terrain Elevation M */
            terrain_elevation_m?: number | null;
            /** Time Index */
            time_index?: number | null;
            /** Time Value */
            time_value?: string | null;
        };
        /** RainfallEventResponse */
        RainfallEventResponse: {
            /** Catalog Generated At Utc */
            catalog_generated_at_utc: string;
            /** Damage Location Name */
            damage_location_name?: string | null;
            /** Damage Location Source Url */
            damage_location_source_url?: string | null;
            /** Data Quality Flags */
            data_quality_flags: string[];
            /** Duration Minutes */
            duration_minutes: number;
            /** Event Date Or Datetime Metadata */
            event_date_or_datetime_metadata?: string | null;
            /** Event Id */
            event_id: string;
            /** Intensity Mm Per H */
            intensity_mm_per_h: number;
            /** Profile Available */
            profile_available: boolean;
            /** Profile Id */
            profile_id?: string | null;
            /** Rank */
            rank?: number | null;
            /** Source Url */
            source_url: string;
            /** Station Id */
            station_id: string;
            /** Station Lat Deg */
            station_lat_deg: number;
            /** Station Lon Deg */
            station_lon_deg: number;
            /** Station Name */
            station_name: string;
            /** Total Precipitation Mm */
            total_precipitation_mm: number;
        };
        /** RainfallExtremesResponse */
        RainfallExtremesResponse: {
            /** Events */
            events: components["schemas"]["RainfallEventResponse"][];
            station: components["schemas"]["RainfallStationResponse"];
        };
        /** RainfallStationResponse */
        RainfallStationResponse: {
            /** Distance Km */
            distance_km?: number | null;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Name */
            name: string;
            /** Prefecture Or Region */
            prefecture_or_region?: string | null;
            /** Station Id */
            station_id: string;
        };
        /** RainfallStationSearchResponse */
        RainfallStationSearchResponse: {
            /** Stations */
            stations: components["schemas"]["RainfallStationResponse"][];
        };
        /** RecentRainfallRankingResponse */
        RecentRainfallRankingResponse: {
            /** Coverage Note */
            coverage_note: string;
            /** Events */
            events: components["schemas"]["RainfallEventResponse"][];
            /** Period End */
            period_end: string;
            /** Period Start */
            period_start: string;
        };
        /** ResourceEstimateRequest */
        ResourceEstimateRequest: {
            /**
             * Accuracy Mode
             * @enum {string}
             */
            accuracy_mode: "full_1m" | "uniform" | "adaptive";
            analysis_area: components["schemas"]["AnalysisArea"];
            /**
             * Grid Cell Size M
             * @default 1
             * @enum {integer}
             */
            grid_cell_size_m: 1 | 2 | 4;
        };
        /** ResourceEstimateResponse */
        ResourceEstimateResponse: {
            /**
             * Estimated Disk Class
             * @enum {string}
             */
            estimated_disk_class: "small" | "medium" | "heavy" | "very_heavy";
            /**
             * Estimated Memory Class
             * @enum {string}
             */
            estimated_memory_class: "small" | "medium" | "heavy" | "very_heavy";
            /** Full 1M Equivalent Cells */
            full_1m_equivalent_cells: number;
            /** Preliminary Adaptive Cells */
            preliminary_adaptive_cells?: number | null;
            /**
             * Runtime Class
             * @enum {string}
             */
            runtime_class: "small" | "medium" | "heavy" | "very_heavy";
            /** Warnings */
            warnings: string[];
        };
        /** ResultDepthLegendItem */
        ResultDepthLegendItem: {
            /** Color */
            color: string;
            /** Label */
            label: string;
            /** Max M */
            max_m?: number | null;
            /** Min M */
            min_m: number;
        };
        /** ResultElevationLegendItem */
        ResultElevationLegendItem: {
            /** Color */
            color: string;
            /** Label */
            label: string;
            /** Max M */
            max_m: number;
            /** Min M */
            min_m: number;
        };
        /** ResultEnergyJobResponse */
        ResultEnergyJobResponse: {
            /**
             * Aggregation Buffer Bytes
             * @default 0
             */
            aggregation_buffer_bytes: number;
            /** Energy */
            energy?: components["schemas"]["ResultExtremeLocation"][];
            /** Error */
            error?: string | null;
            /**
             * Method
             * @default
             */
            method: string;
            /** Processed Frames */
            processed_frames: number;
            /** Progress Percent */
            progress_percent: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "failed";
            /** Total Frames */
            total_frames: number;
        };
        /** ResultEngineSummary */
        ResultEngineSummary: {
            /** Hydromt Sfincs Version */
            hydromt_sfincs_version?: string | null;
            /** Sfincs Build Sha256 */
            sfincs_build_sha256?: string | null;
            /** Sfincs Engine Source */
            sfincs_engine_source?: string | null;
            /** Sfincs Version */
            sfincs_version?: string | null;
        };
        /** ResultExtremaJobResponse */
        ResultExtremaJobResponse: {
            /** Depth */
            depth: components["schemas"]["ResultExtremeLocation"][];
            /** Error */
            error?: string | null;
            /** Processed Frames */
            processed_frames: number;
            /** Progress Percent */
            progress_percent: number;
            /** Speed */
            speed: components["schemas"]["ResultExtremeLocation"][];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "failed";
            /** Total Frames */
            total_frames: number;
        };
        /** ResultExtremaResponse */
        ResultExtremaResponse: {
            /** Depth */
            depth: components["schemas"]["ResultExtremeLocation"][];
            /** Speed */
            speed: components["schemas"]["ResultExtremeLocation"][];
        };
        /** ResultExtremeLocation */
        ResultExtremeLocation: {
            /** Cell Area M2 */
            cell_area_m2: number;
            /** Cell Index */
            cell_index: number;
            /** Depth M */
            depth_m: number;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Rank */
            rank: number;
            /** Speed Mps */
            speed_mps?: number | null;
            /** Time Index */
            time_index: number;
            /** Time Value */
            time_value: string;
            /** Total Energy J */
            total_energy_j?: number | null;
            /** Total Outflow M3 */
            total_outflow_m3?: number | null;
        };
        /** ResultImportResponse */
        ResultImportResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @default COMPLETE
             * @constant
             */
            status: "COMPLETE";
        };
        /** ResultMetadataResponse */
        ResultMetadataResponse: {
            /** Available Time Indices */
            available_time_indices: number[];
            bounds: components["schemas"]["GeoBounds"];
            /** Cache Schema Revision */
            cache_schema_revision?: number | null;
            /** Chunk Shape */
            chunk_shape?: number[] | null;
            /** Depth Legend */
            depth_legend?: components["schemas"]["ResultDepthLegendItem"][];
            /** Display Scales */
            display_scales?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Elevation Legend */
            elevation_legend?: components["schemas"]["ResultElevationLegendItem"][];
            engine_summary?: components["schemas"]["ResultEngineSummary"];
            /**
             * Flow Vectors Available
             * @default false
             */
            flow_vectors_available: boolean;
            /** Grid Level Summary */
            grid_level_summary: {
                [key: string]: number;
            };
            /** Limitations */
            limitations: {
                [key: string]: boolean;
            };
            /** Max Depth Summary */
            max_depth_summary: {
                [key: string]: number;
            };
            /** No Data Policy */
            no_data_policy: string;
            provider_summary?: components["schemas"]["ResultProviderSummary"];
            run_summary: components["schemas"]["ResultRunSummary"];
            /** Schema Version */
            schema_version: string;
            /** Storage Kind */
            storage_kind?: string | null;
            /** Time Values */
            time_values: string[];
            /** Units */
            units: {
                [key: string]: string;
            };
        };
        /** ResultProviderSummary */
        ResultProviderSummary: {
            /** Building Provider */
            building_provider?: string | null;
            /** Road Provider */
            road_provider?: string | null;
            /** Warnings */
            warnings?: string[];
        };
        /** ResultRunSummary */
        ResultRunSummary: {
            /** Application Version */
            application_version: string;
            /** Boundary Policy */
            boundary_policy: string;
            /** Elevation Provider Counts */
            elevation_provider_counts?: {
                [key: string]: number;
            };
            /** Elevation Source Summary */
            elevation_source_summary?: {
                [key: string]: unknown;
            };
            /** Manning Defaults */
            manning_defaults?: {
                [key: string]: number;
            };
            /** Rainfall Source */
            rainfall_source?: {
                [key: string]: unknown;
            };
            /**
             * Requested Accuracy Mode
             * @enum {string}
             */
            requested_accuracy_mode: "full_1m" | "uniform" | "adaptive";
            /** Roof Rain Mass Diagnostic */
            roof_rain_mass_diagnostic?: {
                [key: string]: number;
            };
        };
        /** RunConfig */
        RunConfig: {
            /**
             * Adaptive Max Block Size M
             * @default 4
             * @enum {integer}
             */
            adaptive_max_block_size_m: 1 | 2 | 4;
            analysis_area: components["schemas"]["AnalysisArea"];
            /**
             * Grid Cell Size M
             * @default 1
             * @enum {number}
             */
            grid_cell_size_m: 0.5 | 1 | 2 | 4;
            /** Rainfall */
            rainfall?: (components["schemas"]["ConstantRainfall"] | components["schemas"]["HistoricalUniformRainfall"] | components["schemas"]["HistoricalObservedProfile"]) | null;
            requested_accuracy_mode: components["schemas"]["AccuracyMode"];
            water_magic?: components["schemas"]["WaterMagicConfig"] | null;
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @default QUEUED
             * @constant
             */
            status: "QUEUED";
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "CREATED" | "VALIDATING" | "ACQUIRING_TERRAIN" | "ACQUIRING_VECTORS" | "ACQUIRING_RAINFALL" | "PREPROCESSING_TERRAIN" | "ALLOCATING_ROOF_RAIN" | "BUILDING_GRID" | "BUILDING_MODEL" | "ENSURING_ENGINE" | "RUNNING_ENGINE" | "READING_RESULTS" | "COMPLETE" | "FAILED" | "CANCELLING" | "CANCELLED";
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Activity Lines */
            activity_lines?: string[];
            /** Estimated Remaining Seconds */
            estimated_remaining_seconds?: number | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Progress Detail */
            progress_detail?: string | null;
            /** Progress Fraction */
            progress_fraction?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Stage Code */
            stage_code: string;
            /** Stage Label */
            stage_label: string;
            state: components["schemas"]["RunState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaterMagicConfig */
        WaterMagicConfig: {
            /** Bearing Deg */
            bearing_deg: number;
            /** Casting Seconds */
            casting_seconds: number;
            /**
             * Catalog Revision
             * @default 2026-10-03
             * @constant
             */
            catalog_revision: "2026-10-03";
            /**
             * Footprint Kind
             * @default circle
             * @enum {string}
             */
            footprint_kind: "circle" | "domain" | "rectangle" | "sector";
            /** Generation Rate M3Ps */
            generation_rate_m3ps?: number | null;
            /**
             * Initial Motion
             * @default none
             * @enum {string}
             */
            initial_motion: "none" | "directional" | "radial" | "vortex";
            /**
             * Initial Speed Mps
             * @default 0
             */
            initial_speed_mps: number;
            /**
             * Length M
             * @default 20
             */
            length_m: number;
            position: components["schemas"]["LonLat"];
            /** Radius M */
            radius_m: number;
            /** Relaxation Seconds */
            relaxation_seconds: number;
            /**
             * Release Mode
             * @default continuous
             * @enum {string}
             */
            release_mode: "continuous" | "initial";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /**
             * Sector Angle Deg
             * @default 90
             */
            sector_angle_deg: number;
            /**
             * Spell Id
             * @default healing-rain
             * @enum {string}
             */
            spell_id: "healing-rain" | "gw2-healingrain" | "ff3-tsunami" | "warcraft1-elemental" | "chrono-water2" | "ff7-tidalwave" | "ro-waterball5" | "warcraft3-elemental" | "tales-tidalwave" | "lol-nami-wave" | "dos2-rain" | "kh3-waterga" | "genshin-mona" | "genshin-neuvillette" | "forspoken-cataract" | "bg3-createwater" | "wow-elemental" | "dq7-maelstrom" | "ff6-flood" | "ff15-tsunami" | "chrono-cross-deluge" | "goldensun-neptune" | "rs3-maelstrom" | "school-pool" | "kaiju-godzilla-wave" | "kaiju-titanosaurus-vortex";
            /** Volume M3 */
            volume_m3: number;
            /**
             * Vortex Core Radius M
             * @default 2
             */
            vortex_core_radius_m: number;
            /**
             * Vortex Direction
             * @default clockwise
             * @enum {string}
             */
            vortex_direction: "clockwise" | "counterclockwise";
            /**
             * Width M
             * @default 10
             */
            width_m: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_config_api_v1_app_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfigResponse"];
                };
            };
        };
    };
    open_demo_result_api_v1_demo_results__event_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_elevation_preview_api_v1_elevation_previews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevationPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElevationPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_resources_api_v1_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    rainfall_event_api_v1_rainfall_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_rainfall_ranking_api_v1_rainfall_recent_ranking_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentRainfallRankingResponse"];
                };
            };
        };
    };
    rainfall_stations_api_v1_rainfall_stations_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallStationSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rainfall_station_extremes_api_v1_rainfall_stations__station_id__extremes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallExtremesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_result_api_v1_results_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultImportResponse"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_result_api_v1_runs__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_result_api_v1_runs__run_id__inspect_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
                time_index?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_depth_layer_api_v1_runs__run_id__layers_depth_png_get: {
        parameters: {
            query: {
                time_index: number;
                max_px?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elevation_layer_api_v1_runs__run_id__layers_elevation_png_get: {
        parameters: {
            query?: {
                max_px?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grid_resolution_layer_api_v1_runs__run_id__layers_grid_resolution_png_get: {
        parameters: {
            query?: {
                max_px?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    max_depth_layer_api_v1_runs__run_id__layers_max_depth_png_get: {
        parameters: {
            query?: {
                max_px?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_energy_status_api_v1_runs__run_id__result_energy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultEnergyJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_result_energy_api_v1_runs__run_id__result_energy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultEnergyJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_energy_point_api_v1_runs__run_id__result_energy_point_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointEnergyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_extrema_api_v1_runs__run_id__result_extrema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultExtremaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_result_extrema_api_v1_runs__run_id__result_extrema_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultExtremaJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_extrema_status_api_v1_runs__run_id__result_extrema_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultExtremaJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_metadata_api_v1_runs__run_id__result_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
